server:
    port: 8081
spring:
    dubbo:
        application:
            name: mixiusi-service
        base-package: com.mixiusi.service  # dubbo服务发布者实现类注解@service所在的包
        registry:
            address: 116.62.143.72:2181,192.168.0.105:2181                 # zookeeper注册中心的地址
            #port: 2181                          # zookeeper注册中心的端口
        protocol:
            name: dubbo  #适合于小数据量大并发的服务调用，以及服务消费者机器数远大于服务提供者机器数的情况
            serialization: hessian2
        provider:
            retries: 0                           # 服务调用重试次数，服务发布者不给重试，让服务调用者自己重试

    datasource:
        url: jdbc:mysql://47.98.164.44:3306/coffeemachine?useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            initial-size: 8
            min-idle: 5
            max-active: 10
            query-timeout: 6000
            transaction-query-timeout: 6000
            remove-abandoned-timeout: 1800
            filter-class-names: stat
            filters: stat,config
            
    jpa:
        hibernate:
            show-sql: true
            ddl-auto: update
            management.security.enabled: false
            
            
            
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        
#  datasource:
#    write:
#      url: jdbc:mysql://127.0.0.1:3306/platform?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver
#      max-active: 20
#      initial-size: 1
#      min-idle: 3
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x' FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filters: stat,wall,log4j
#      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
#      # 合并多个DruidDataSource的监控数据
#      #spring.datasource.useGlobalDataSourceStat=true
#    read:
#      url: jdbc:mysql://127.0.0.1:3306/platform?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver
#      max-active: 20
#      initial-size: 1
#      min-idle: 3
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x' FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filters: stat,wall,log4j
#      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
#      # 合并多个DruidDataSource的监控数据
#      #spring.datasource.useGlobalDataSourceStat=true